apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: install-crossplane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://8AB35FAEE58366632D062F4F7706F316.sk1.us-west-2.eks.amazonaws.com'
    namespace: crossplane-system
  project: default
  source:
    repoURL: 'https://git-bitbucket.aws.fico.com:8443/scm/gitops/crossplane_conf.git'
    targetRevision: HEAD
    path: demo/crossplane/crossplane
    helm:
      valueFiles:
        - sandbox-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true