apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dynamic-elements
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: main
    path: dynamic-elements/argocd
    directory:
      recurse: true
  destination:
    name: sandbox
    namespace: argocd