apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dynamic-elements
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/Yatin03/ArgoCD.git
    targetRevision: HEAD
    path: dynamic-elements/argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd