apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Yatin03/ArgoCD.git
    targetRevision: HEAD
    path: development
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true