apiVersion: batch/v1
kind: Job
metadata:
  name: postdelete
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook: PostDelete
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "25"]
      restartPolicy: Never
  backoffLimit: 0