apiVersion: batch/v1
kind: Job
metadata:
  name: syncFailed
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "15"]
      restartPolicy: Never
  backoffLimit: 0