apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      name: nginx
      ports:
        - containerPort: 80
