apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  source:
    path: apps-of-apps/argocd-apps
    repoURL: https://github.com/Yatin03/ArgoCD.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true