# apiVersion: aws.crossplane.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: awsconfig
# spec:
#   credentials:
#     secretRef:
#       key: credentials
#       name: aws-secret-creds
#       namespace: crossplane-system
#     source: Secret