apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: apps-of-apps/app-3
    repoURL: https://github.com/Yatin03/ArgoCD.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # dependencies:
  # - name: my-apps-2
  #   namespace: argocd