apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: demo-test-instance1
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-2
    imageId: ami-07321d250855f25bb
    instanceType: t2.micro
    networkInterfaces:
    - subnetId: subnet-09f0d6eaa3b7ebb30
      deviceIndex: 0
      groups:
      - sg-073cd963e1064a4df
      interfaceType: interface
  providerConfigRef:
    name: aws-provider-config